name: madeline-journey

services:
  caddy:
    container_name: caddy
    image: caddy
    restart: always
    ports:
      - '8080:80'
      - '4433:443'
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./front/dist:/usr/share/caddy
  api:
    build: ./api
    environment:
      - DB=postgresql://madeline:madeline@db/madeline-journey
      - JWT_SECRET=madeline-is-the-best-and-its-a-super-secret
    restart: unless-stopped
    depends_on:
      - db
  db:
    restart: unless-stopped
    image: postgres:12-alpine
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U madeline -d madeline-journey']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 40s
    environment:
      POSTGRES_PASSWORD: madeline
      POSTGRES_USER: madeline
      POSTGRES_DB: madeline-journey
      TZ: Europe/Paris
      PGTZ: Europe/Paris
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  caddy-config:
  caddy-data:
  db-data:
    driver: local
