name: madeline-journey-dev

services:
  caddy:
    image: caddy
    restart: always
    ports:
      - "8080:80"
      - "4433:443"
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - ./tools/docker/caddy/Caddyfile.dev:/etc/caddy/Caddyfile:ro
    depends_on:
      - api
      - front
  api:
    image: cosmtrek/air
    volumes:
      - ./api:/go/src/app
    environment:
      - DB=postgresql://madeline:madeline@db/madeline-journey
      - JWT_SECRET=madeline-is-the-best-and-its-a-super-secret
      - MAILSERVER_HOST=maildev:1025
    restart: unless-stopped
    working_dir: /go/src/app
    depends_on:
      - db
  front:
    build:
      context: ./tools/docker/node
    restart: unless-stopped
    command: pnpm run dev
    working_dir: /usr/src/app
    volumes:
      - ./front:/usr/src/app
  db:
    restart: unless-stopped
    image: postgres:12-alpine
    healthcheck:
      test: ["CMD-SHELL", "pgsql -U madeline -d madeline-journey"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 40s
    environment:
      POSTGRES_PASSWORD: madeline
      POSTGRES_USER: madeline
      POSTGRES_DB: madeline-journey
      TZ: Europe/Paris
      PGTZ: Europe/Paris
    volumes:
      - db-data:/var/lib/postgresql/data
  maildev:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    restart: unless-stopped

volumes:
  caddy-config:
  caddy-data:
  db-data:
    driver: local
