name: madeline-journey-dev

services:
  caddy:
    image: caddy
    restart: always
    ports:
      - '8080:80'
      - '4433:443'
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
    depends_on:
      - api
      - front
  api:
    image: cosmtrek/air
    volumes:
      - ./api:/go/src/app
    environment:
      - DB=postgresql://madeline:madeline@db/madeline-journey
      - JWT_SECRET=madeline-is-the-best-and-its-a-super-secret
    restart: unless-stopped
    working_dir: /go/src/app
    depends_on:
      - db
  front:
    image: node:latest
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./front:/app
    command: 'npm run dev -- --host'
  db:
    restart: unless-stopped
    image: postgres:12-alpine
    healthcheck:
      test: ['CMD-SHELL', 'pgsql -U madeline -d madeline-journey']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 40s
    environment:
      POSTGRES_PASSWORD: madeline
      POSTGRES_USER: madeline
      POSTGRES_DB: madeline-journey
      TZ: Europe/Paris
      PGTZ: Europe/Paris
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  caddy-config:
  caddy-data:
  db-data:
    driver: local
